FacturaApp/Controllers/FacturaController.cs
using FacturaApp.Models;
using FacturaApp.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FacturaApp.Controllers
{
    public class FacturaController : Controller
    {
        // GET: Factura

        public ActionResult Index()
        {
            List<ClienteDetalleViewModel> lst = new List<ClienteDetalleViewModel>();

            using (FacturaAppBdContext db = new FacturaAppBdContext())
            {
                lst = (from d in db.Facturas
                       join c in db.Clientes on d.ClienteId equals c.ClienteId
                      
                       select new ClienteDetalleViewModel
                       {
                           IDFactura = d.FacturaId,
                           Cliente = c.Nombre + " " + c.Apellido,
                           Fecha = d.Fecha,
                       }).ToList();
            }
            return View(lst);
        }

        [HttpGet]
        public ActionResult Registrar()
        {
            return View();

        }

        [HttpGet]
        public ActionResult BuscarProducto()
        {
            using (FacturaAppBdContext db = new FacturaAppBdContext())
            {
                return Json(db.Productos.Select(x => new
                {
                    ProductoId = x.ProductoId,
                    Nombre = x.Nombre,
                    PrecioVenta = x.PrecioVenta

                }).ToList(), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult BuscarCliente()
        {
            using (FacturaAppBdContext db = new FacturaAppBdContext())
            {
                return Json(db.Clientes.Select(x => new
                {
                    ClienteId = x.ClienteId,
                    NombreCompleto = x.Nombre + " " + x.Apellido

                }).ToList(), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult Registrar(FacturaViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {

                using (FacturaAppBdContext db = new FacturaAppBdContext())
                {
                    Factura oFactura = new Factura();
                    oFactura.ClienteId = model.ClienteId;
                    oFactura.Fecha = DateTime.Now;
                    db.Facturas.Add(oFactura);
                    db.SaveChanges();

                    foreach (var item in model.DetalleFacturaViewModels)
                    {
                        DetalleFactura oDetalleFactura = new DetalleFactura();
                        oDetalleFactura.ProductoId = item.ProductoId;
                        oDetalleFactura.Cantidad = item.Cantidad;
                        oDetalleFactura.Total = item.Precio * item.Cantidad;
                        oDetalleFactura.FacturaId = oFactura.FacturaId;
                        db.DetalleFacturas.Add(oDetalleFactura);
                    }

                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(model);
                throw;
            }
        }


        //[HttpGet]
        //public ActionResult DetalleCliente(int id)
        //{
        //    List<ClienteDetalleViewModel> lst = new List<ClienteDetalleViewModel>();

        //    using (FacturaAppBdContext db = new FacturaAppBdContext())
        //    {
        //        lst = (from d in db.Facturas
        //               join c in db.Clientes on d.ClienteId equals c.ClienteId
        //               join f in db.DetalleFacturas on d.FacturaId equals f.FacturaId
        //               where d.ClienteId == id

        //               select new ClienteDetalleViewModel 
        //               {
        //                   IDFactura = d.FacturaId,
        //                   Cliente = c.Nombre + " " + c.Apellido,
        //                   Fecha = d.Fecha,
        //               }).ToList();
        //    }


        //    return View(lst);
        //}
        [HttpGet]
        public ActionResult DetalleCliente()
        {
           


            return View();
        }
    }
}

FacturaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FacturaApp</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <nav class="navbar is-fixed-top is-primary" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">

            <a class="navbar-item" href="https://bulma.io">
            
                <h1 class="title is-4">FacturaApp</h1>
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">

                @Html.ActionLink("Categoria", "Index", "Categoria", null, new { @class = "navbar-item" })
                @Html.ActionLink("Producto", "Index", "Producto", null, new { @class = "navbar-item" })
                @Html.ActionLink("Cliente", "Index", "Cliente", null, new { @class = "navbar-item" })
                @Html.ActionLink("Hacer Venta", "Index", "Factura", null, new { @class = "navbar-item" })       
            </div>

        </div>
    </nav>

    <div class="container is-desktop">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Julio Sánchez</p>
        </footer>
    </div>
 
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>